# syntax=docker/dockerfile:1
FROM golang:1.22-alpine AS builder
WORKDIR /src
ENV GOTOOLCHAIN=auto
RUN apk add --no-cache ca-certificates git
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /bin/client ./cmd/client

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=builder /bin/client /bin/client
ENTRYPOINT ["/bin/client"]
